In [7]:
import pandas as pd

In [9]:
df=pd.read_csv('../data/sample_data.csv')
df.head()

  customer_id order_id  order_date  amount       city
0        C001     O101  2023-01-01     250      Delhi
1        C002     O102  2023-01-03     450     Mumbai
2        C003     O103  2023-01-05     300  Bangalore
3        C001     O104  2023-01-07     200      Delhi
4        C004     O105  2023-01-10     500    Chennai

In [10]:
df.tail()

   customer_id order_id  order_date  amount       city
10        C008     O111  2023-01-25     600      Delhi
11        C001     O112  2023-01-27     100      Delhi
12        C009     O113  2023-01-29     900     Mumbai
13        C010     O114  2023-02-01     750  Bangalore
14        C005     O115  2023-02-03     650    Kolkata

In [11]:
df. describe()

           amount
count   15.000000
mean   473.333333
std    251.329797
min    100.000000
25%    275.000000
50%    450.000000
75%    675.000000
max    900.000000

In [12]:
df.info(
    
)

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  15 non-null     str
 1   order_id     15 non-null     str
 2   order_date   15 non-null     str
 3   amount       15 non-null     int64
 4   city         15 non-null     str
dtypes: int64(1), str(4)
memory usage: 732.0 bytes

In [13]:
def f(a):
    return a+100
df['TotalAmount']=df['amount'].apply(f)

In [14]:
df.head(
    
)

  customer_id order_id  order_date  amount       city  TotalAmount
0        C001     O101  2023-01-01     250      Delhi          350
1        C002     O102  2023-01-03     450     Mumbai          550
2        C003     O103  2023-01-05     300  Bangalore          400
3        C001     O104  2023-01-07     200      Delhi          300
4        C004     O105  2023-01-10     500    Chennai          600

In [15]:
df1=pd.DataFrame({"id":[1,2,3],"name":["A","B","C"]})

In [16]:
df2=pd.DataFrame({"id":[1,2,3],"marks":[23,34,56]})

In [17]:
df1.head()

   id name
0   1    A
1   2    B
2   3    C

In [18]:
df2.head(
    
)

   id  marks
0   1     23
1   2     34
2   3     56

In [22]:
pd.concat([df1,df2],axis=0)

   id name  marks
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   23.0
1   2  NaN   34.0
2   3  NaN   56.0

In [23]:
pd.merge(df1,df2, on='id')

   id name  marks
0   1    A     23
1   2    B     34
2   3    C     56

In [24]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [25]:
df.head()

  customer_id order_id order_date  amount       city  TotalAmount
0        C001     O101 2023-01-01     250      Delhi          350
1        C002     O102 2023-01-03     450     Mumbai          550
2        C003     O103 2023-01-05     300  Bangalore          400
3        C001     O104 2023-01-07     200      Delhi          300
4        C004     O105 2023-01-10     500    Chennai          600

In [26]:
df[df['amount'] > 500]

   customer_id order_id order_date  amount       city  TotalAmount
5         C005     O106 2023-01-12     700    Kolkata          800
7         C006     O108 2023-01-18     800  Hyderabad          900
10        C008     O111 2023-01-25     600      Delhi          700
12        C009     O113 2023-01-29     900     Mumbai         1000
13        C010     O114 2023-02-01     750  Bangalore          850
14        C005     O115 2023-02-03     650    Kolkata          750

In [27]:
df['high_value'] = df['amount'] > 500

In [28]:
df.head()

  customer_id order_id order_date  amount       city  TotalAmount  high_value
0        C001     O101 2023-01-01     250      Delhi          350       False
1        C002     O102 2023-01-03     450     Mumbai          550       False
2        C003     O103 2023-01-05     300  Bangalore          400       False
3        C001     O104 2023-01-07     200      Delhi          300       False
4        C004     O105 2023-01-10     500    Chennai          600       False

In [29]:
df['customer_id'].value_counts()

customer_id
C001    3
C002    2
C003    2
C005    2
C004    1
C006    1
C007    1
C008    1
C009    1
C010    1
Name: count, dtype: int64

In [30]:
df.sort_values(by='amount', ascending=False)

   customer_id order_id order_date  amount       city  TotalAmount  high_value
12        C009     O113 2023-01-29     900     Mumbai         1000        True
7         C006     O108 2023-01-18     800  Hyderabad          900        True
13        C010     O114 2023-02-01     750  Bangalore          850        True
5         C005     O106 2023-01-12     700    Kolkata          800        True
14        C005     O115 2023-02-03     650    Kolkata          750        True
10        C008     O111 2023-01-25     600      Delhi          700        True
4         C004     O105 2023-01-10     500    Chennai          600       False
1         C002     O102 2023-01-03     450     Mumbai          550       False
9         C007     O110 2023-01-22     400       Pune          500       False
8         C003     O109 2023-01-20     350  Bangalore          450       False
2         C003     O103 2023-01-05     300  Bangalore          400       False
0         C001     O101 2023-01-01     250      Delhi          350       False
3         C001     O104 2023-01-07     200      Delhi          300       False
6         C002     O107 2023-01-15     150     Mumbai          250       False
11        C001     O112 2023-01-27     100      Delhi          200       False

In [31]:
df.groupby('city').agg({
    'amount': ['sum', 'mean', 'count']
})

          amount
             sum        mean count
city
Bangalore   1400  466.666667     3
Chennai      500  500.000000     1
Delhi       1150  287.500000     4
Hyderabad    800  800.000000     1
Kolkata     1350  675.000000     2
Mumbai      1500  500.000000     3
Pune         400  400.000000     1

In [32]:
df=pd.read_csv('../data/sample_data.csv')
df.head()

  customer_id order_id  order_date  amount       city
0        C001     O101  2023-01-01     250      Delhi
1        C002     O102  2023-01-03     450     Mumbai
2        C003     O103  2023-01-05     300  Bangalore
3        C001     O104  2023-01-07     200      Delhi
4        C004     O105  2023-01-10     500    Chennai

In [33]:
df=pd.read_csv('../data/orders_dataset.csv')
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [34]:
df.info()
df.isnull().sum()
df.duplicated().sum()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       499 non-null    str
 1   customer_id                    499 non-null    str
 2   order_status                   499 non-null    str
 3   order_purchase_timestamp       499 non-null    str
 4   order_approved_at              499 non-null    str
 5   order_delivered_carrier_date   492 non-null    str
 6   order_delivered_customer_date  482 non-null    str
 7   order_estimated_delivery_date  499 non-null    str
dtypes: str(8)
memory usage: 31.3 KB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [35]:
df.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                 0
order_delivered_carrier_date      7
order_delivered_customer_date    17
order_estimated_delivery_date     0
dtype: int64

In [36]:
df = df.drop_duplicates()

date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

df['order_status'] = df['order_status'].str.strip().str.lower()

df = df.dropna(subset=['order_id', 'customer_id'])

df['delivery_delay_days'] = (
    df['order_delivered_customer_date'] - df['order_estimated_delivery_date']
).dt.days

In [37]:
df.head()

df.to_csv('../data/cleaned_orders_dataset.csv', index=False)

In [39]:
df = pd.read_csv('../data/customer_dataset.csv')

df.drop_duplicates(inplace=True)

df['customer_city'] = df['customer_city'].str.strip().str.lower()
df['customer_state'] = df['customer_state'].str.strip().str.upper()

df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [40]:
df.to_csv('../data/cleaned_customer_dataset.csv', index=False)

In [41]:
df = pd.read_csv('../data/payments_dataset.csv')

df.drop_duplicates(inplace=True)

df['payment_type'] = df['payment_type'].str.strip().str.lower()

# ensure numeric
df['payment_value'] = pd.to_numeric(df['payment_value'], errors='coerce')

df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [42]:
df.to_csv('../data/cleaned_payments_dataset.csv', index=False)

In [43]:
df = pd.read_csv('../data/order_items_dataset.csv')

df.drop_duplicates(inplace=True)

df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['freight_value'] = pd.to_numeric(df['freight_value'], errors='coerce')

df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [44]:
df.to_csv('../data/cleaned_order_items_dataset.csv', index=False)

In [45]:
df = pd.read_csv('../data/products_dataset.csv')

df.drop_duplicates(inplace=True)

df['product_category_name'] = df['product_category_name'].str.strip().str.lower()

df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625,20,17,13

In [46]:
df.to_csv('../data/cleaned_products_dataset.csv', index=False)

In [47]:
import pandas as pd

df = pd.read_csv('../data/olist_orders_dataset.csv')

# remove exact duplicates
df.drop_duplicates(inplace=True)

# convert datetime columns safely
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# standardize text
df['order_status'] = df['order_status'].str.strip().str.lower()

# DO NOT drop rows here (important)

# optional derived column (keep for analysis, ignore in SQL load)
df['delivery_delay_days'] = (
    df['order_delivered_customer_date'] - df['order_estimated_delivery_date']
).dt.days

df.to_csv('../data/cleaned_orders_dataset.csv', index=False)

In [48]:
df = pd.read_csv('../data/olist_customers_dataset.csv')

df.drop_duplicates(inplace=True)

# standardize location
df['customer_city'] = df['customer_city'].str.strip().str.lower()
df['customer_state'] = df['customer_state'].str.strip().str.upper()

# DO NOT drop rows

df.to_csv('../data/cleaned_customers_dataset.csv', index=False)

In [49]:
df = pd.read_csv('../data/olist_payments_dataset.csv')

df.drop_duplicates(inplace=True)

# clean categorical
df['payment_type'] = df['payment_type'].str.strip().str.lower()

# ensure numeric
df['payment_value'] = pd.to_numeric(df['payment_value'], errors='coerce')
df['payment_installments'] = pd.to_numeric(df['payment_installments'], errors='coerce')

df.to_csv('../data/cleaned_payments_dataset.csv', index=False)

In [50]:
df = pd.read_csv('../data/olist_order_items_dataset.csv')

df.drop_duplicates(inplace=True)

df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['freight_value'] = pd.to_numeric(df['freight_value'], errors='coerce')

# optional: convert shipping date
df['shipping_limit_date'] = pd.to_datetime(df['shipping_limit_date'], errors='coerce')

df.to_csv('../data/cleaned_order_items_dataset.csv', index=False)

In [51]:
df = pd.read_csv('../data/olist_products_dataset.csv')

df.drop_duplicates(inplace=True)

df['product_category_name'] = df['product_category_name'].str.strip().str.lower()

# keep only needed columns for SQL
df = df[['product_id', 'product_category_name', 'product_weight_g']]

df.to_csv('../data/cleaned_products_dataset.csv', index=False)